#!/usr/bin/env python3
"""gen_variation.py -- params.json -> variation_<run_id>.lua

Emits the per-run variation script applied to the loaded baseline (step 3 of
the workflow in README.md). Covers: logger init, EMCON, magazine levels, and
time-triggered wave-launch events for UNIT-type OWEs.

Deliberately a stub where marked: wave-launch spawn code depends on the
owe_kind fork (README gotcha 4) and on the dbid/loadout you resolve in your
own DB build.

Usage: python gen_variation.py params.example.json
"""

import json
import sys
from pathlib import Path

LUA_HEADER = """\
-- variation_{run_id}.lua  (generated by gen_variation.py -- do not hand-edit)
-- Apply to the loaded owe_baseline.scen AFTER owe_log.lua + owe_wiring.lua.

OweLog.init('{run_id}', '{out_dir}', '{blue}')
ScenEdit_SetKeyValue('owe_run_notes', '{notes}')

-- Defence posture -----------------------------------------------------------
ScenEdit_SetEMCON('Side', '{blue}', '{emcon}')
"""

MAG_TEMPLATE = """\
-- {unit}: set {wname} -> {rounds}
-- NB: exact magazine-fill API differs by build; the reliable manual fallback
-- is unit editor -> magazines. Scripted route (verify field names):
do
  local ok, err = pcall(function()
    local u = ScenEdit_GetUnit({{ side = '{blue}', name = '{unit}' }})
    -- TODO(verify): ScenEdit_SetMagazine / mag wrapper assignment for your
    -- build; log the working incantation in lessons-learned.md.
  end)
  if not ok then
    ScenEdit_SpecialMessage('{blue}', 'MAG SET FAILED {unit}: ' .. tostring(err))
  end
end
"""

WAVE_EVENT_TEMPLATE = """\
-- Wave {idx}: {size} x OWE, axis {axis}, T+{t_offset_min} min ---------------
do
  local t = ScenEdit_CurrentTime() + {t_offset_sec}
  ScenEdit_SetTrigger({{ mode = 'add', name = 'TRG_WAVE_{idx}',
                         type = 'Time', time = t }})
  ScenEdit_SetAction({{ mode = 'add', type = 'LuaScript',
                        name = 'ACT_WAVE_{idx}', ScriptText = [==[
    -- Spawn {size} unit-type OWEs in-flight at {launch_site}, staggered
    -- {spacing_s}s apart, assigned to the pre-built '{axis}' strike mission.
    -- Staggering inside one action: spawn all now but offset along the lane,
    -- OR create one sub-event per airframe at generation time (cleaner).
    for i = 1, {size} do
      local name = string.format('{prefix}-{axis_short}-%03d',
                                 i + {name_offset})
      local u = ScenEdit_AddUnit({{
        side = '{red}', type = 'Aircraft', name = name,
        dbid = {owe_dbid}, loadoutid = nil,   -- TODO: resolve in your DB
        latitude = {ls_lat}, longitude = {ls_lon},
        altitude = {altitude_m}, speed = {speed_kts},
        -- TODO(verify): in-flight spawn field for your build
      }})
      if u ~= nil then
        pcall(ScenEdit_AssignUnitToMission, name, '{axis} Strike')
        OweLog.row('owe_launch', {{ side = '{red}', unit = name,
                                    detail = 'wave={idx};axis={axis}' }})
      else
        ScenEdit_SpecialMessage('{red}', 'SPAWN FAILED wave {idx}: ' .. name)
      end
    end
  ]==] }})
  ScenEdit_SetEvent('WAVE_{idx}', {{ mode = 'add', IsShown = false,
                                     IsRepeatable = false }})
  ScenEdit_SetEventTrigger('WAVE_{idx}', {{ mode = 'add', name = 'TRG_WAVE_{idx}' }})
  ScenEdit_SetEventAction('WAVE_{idx}',  {{ mode = 'add', name = 'ACT_WAVE_{idx}' }})
end
"""


def main(params_path: str) -> None:
    p = json.loads(Path(params_path).read_text())
    run, raid, dfc, log = p["run"], p["raid"], p["defence"], p["logging"]

    if raid["owe_kind"] != "unit":
        sys.exit("weapon-type OWE launch generation not implemented -- "
                 "see README gotcha 4 before choosing this fork.")

    # Launch-site coordinates: resolved at apply time in a real build; the
    # stub expects them added to params as raid.launch_site_coords.
    ls_coords = raid.get("launch_site_coords", {})

    out = [LUA_HEADER.format(
        run_id=run["run_id"], out_dir=log["out_dir"],
        blue=dfc["side"], emcon=dfc["emcon"],
        notes=run.get("notes", "").replace("'", ""))]

    for g in dfc["gbad"]:
        for wname, rounds in g["magazines"].items():
            out.append(MAG_TEMPLATE.format(
                blue=dfc["side"], unit=g["unit"], wname=wname, rounds=rounds))

    name_offset = 0
    for i, w in enumerate(p["raid"]["waves"], start=1):
        coords = ls_coords.get(w["launch_site"], {"lat": 0.0, "lon": 0.0})
        out.append(WAVE_EVENT_TEMPLATE.format(
            idx=i, size=w["size"], axis=w["axis"],
            axis_short=w["axis"][0], launch_site=w["launch_site"],
            t_offset_min=w["t_offset_min"], t_offset_sec=w["t_offset_min"] * 60,
            spacing_s=w["spacing_s"], altitude_m=w["altitude_m"],
            speed_kts=w["speed_kts"], owe_dbid=raid["owe_dbid"],
            prefix=raid["owe_name_prefix"], red="Red",
            name_offset=name_offset,
            ls_lat=coords["lat"], ls_lon=coords["lon"]))
        name_offset += w["size"]

    dest = Path(f"variation_{run['run_id']}.lua")
    dest.write_text("\n".join(out))
    print(f"wrote {dest}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
